name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: bitte-desktop_${{ github.ref_name }}_amd64.deb
          - os: macos-latest
            artifact_name: Bitte.Desktop_${{ github.ref_name }}_aarch64.dmg
          - os: windows-latest
            artifact_name: Bitte.Desktop_${{ github.ref_name }}_x64.msi

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build the app
        run: pnpm build:release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: src/download/*

  create-release:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts/
          pattern: Bitte.Desktop_*.dmg,Bitte.Desktop_*.msi,bitte-desktop_*.deb

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/*.dmg
            ./artifacts/*.msi
            ./artifacts/*.deb
          draft: false
          prerelease: false
          generate_release_notes: true